apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs-kubernetes-workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vayvanna/idp-ish-2-infra
    targetRevision: HEAD
    path: current-state/kubernetes/workloads/tenants  # Point this to where your apps live
    director:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc # IMPORTANT: Root app stays on Management!
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
