apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-owner
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Lower numbers go first
spec:
  enforcementAction: dryrun # by default I think its deny.
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["owner-email"]