apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.teamName }}
  labels:
    # We remove owner-email from here because of the "@" symbol restriction
    managed-by: vayvanna-idp
    team-id: {{ .Values.teamName }} 
  annotations:
    # Annotations allow the '@' character!
    owner-email: {{ .Values.ownerEmail | quote }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: {{ .Values.teamName }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    pods: "20"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-admin-binding
  namespace: {{ .Values.teamName }}
subjects:
- kind: User
  name: {{ .Values.ownerEmail }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io