apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.teamName }}
  labels:
    owner-email: {{ .Values.ownerEmail | quote }}
    managed-by: vayvanna-idp
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: {{ .Values.teamName }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    pods: "20"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-admin-binding
  namespace: {{ .Values.teamName }}
subjects:
- kind: User
  name: {{ .Values.ownerEmail }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin # Gives them power inside THEIR namespace only
  apiGroup: rbac.authorization.k8s.io
