apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.appName }}.{{ .Values.teamName }}.workloads.example.com`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 443
          # Direct reference to the object in the same namespace
          serversTransport: vcluster-transport 
  tls:
    # This tells Traefik to use the secret created by cert-manager
    secretName: "tls-{{ .Values.appName }}-vcluster"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-{{ .Values.appName }}-vcluster"
  namespace: {{ .Release.Namespace }}
spec:
  secretName: "tls-{{ .Values.appName }}-vcluster"
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.appName }}.{{ .Values.teamName }}.workloads.example.com"