apiVersion: v1
kind: Service
metadata:
  name: vcluster-loadbalancer
  namespace: team-alpha # Use the namespace where you installed vcluster
spec:
  selector:
    app: vcluster
    release: {{ .Release.Name }} # This must match your Helm release name
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer