apiVersion: v1
kind: Service
metadata:
  name: team-alpha-lb
  namespace: team-alpha
spec:
  type: LoadBalancer
  selector:
    app: vcluster
    release: team-alpha-preview-env
  ports:
    - name: https
      port: 443
      targetPort: 8443   # vCluster binary listens here
    - name: kubelet
      port: 10250
      targetPort: 8443   # Internal vCluster proxy handles this too