# this file might be either:
#   -> straight yaml:
#       type of resources needed + its data
#         -> so that a CI creates full manifests(that are tiny, KubeVela Applications)
#            and stores em in the ./manifests
# 
#   -> or actual tiny manifest(KubeVela) Application[s])
