apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-workloads
  namespace: argocd
spec:
  project: default
  sources:
    # Source 1: The official Helm Chart
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.13.3
      helm:
        parameters:
          - name: installCRDs
            value: "true"
    # Source 2: Your local Git folder for the Issuer/Secret
    - repoURL: https://github.com/Vayvanna/idp-ish-2-infra
      path: current-state/kubernetes/core/apps/cert-manager
      targetRevision: HEAD
  destination:
    name: workloads-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
