apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5" # Lower numbers go first
spec:
  project: default
  source:
    repoURL: https://github.com/Vayvanna/idp-ish-2-infra/ # Point to your infra repo
    targetRevision: HEAD
    path: current-state/kubernetes/core/apps/gatekeeper # The folder we're about to create
  destination:
    name: workloads-cluster
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
